In [7]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size=10000

In [11]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [12]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[274, 6742, 326, 7190],
 [274, 6742, 326, 5506],
 [274, 3241, 326, 6491],
 [9032, 5999, 8807, 9676, 5188],
 [9032, 5999, 8807, 9676, 1834],
 [1833, 274, 9481, 326, 3343],
 [6198, 4586, 1453, 9676]]

In [13]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [14]:
import numpy as np

In [15]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  274 6742  326 7190]
 [   0    0    0    0  274 6742  326 5506]
 [   0    0    0    0  274 3241  326 6491]
 [   0    0    0 9032 5999 8807 9676 5188]
 [   0    0    0 9032 5999 8807 9676 1834]
 [   0    0    0 1833  274 9481  326 3343]
 [   0    0    0    0 6198 4586 1453 9676]]


In [16]:
## feature representation
dim=10

In [17]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

c:\Users\om\OneDrive\Desktop\Network security\venv\lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step


array([[[-0.01323379,  0.03653565,  0.03527695, -0.04701488,
         -0.00962775, -0.00915177, -0.04973343,  0.03147311,
         -0.04199455,  0.01983353],
        [-0.01323379,  0.03653565,  0.03527695, -0.04701488,
         -0.00962775, -0.00915177, -0.04973343,  0.03147311,
         -0.04199455,  0.01983353],
        [-0.01323379,  0.03653565,  0.03527695, -0.04701488,
         -0.00962775, -0.00915177, -0.04973343,  0.03147311,
         -0.04199455,  0.01983353],
        [-0.01323379,  0.03653565,  0.03527695, -0.04701488,
         -0.00962775, -0.00915177, -0.04973343,  0.03147311,
         -0.04199455,  0.01983353],
        [-0.03444127, -0.04892569,  0.0415051 ,  0.00467945,
         -0.01652174, -0.00900779, -0.00256183,  0.04736609,
         -0.00927512,  0.00519166],
        [ 0.03770122,  0.02997491,  0.00560139, -0.03113472,
         -0.02809341, -0.03765436,  0.00935072, -0.00834478,
         -0.02622631, -0.00912924],
        [-0.01403588,  0.04641867, -0.00745331, -0.0

In [20]:
embedded_docs[0]

array([   0,    0,    0,    0,  274, 6742,  326, 7190])

In [21]:
model.predict(embedded_docs[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None
  • kwargs=<class 'inspect._empty'>